In [1]:
# 7-9-2026

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import kendalltau, spearmanr
import matplotlib.pyplot as plt

In [3]:
true_matrix = pd.read_csv("../transfer-matrix/rf_transfer_matrix.csv")
pred_matrix = pd.read_csv("../training/predicted_transfer_matrix_v3.csv")

In [4]:
true_matrix.set_index("Unnamed: 0", inplace=True)
true_matrix.index.name = None
true_matrix

,0,1,2,4,5,6,7,8,11,12,...,32,33,36,37,38,39,45,46,47,49
0,0.392727,0.291660,0.127238,0.058840,0.214817,0.084705,0.149056,0.182358,0.173877,0.026375,...,0.228505,0.243433,0.149609,0.275203,0.112525,-0.011557,0.116862,0.158796,0.025454,0.029928
1,0.142172,0.395760,0.030643,0.010376,0.180707,0.064432,0.056092,0.128808,0.097788,0.039590,...,0.167477,0.032806,0.029704,0.193033,0.055264,0.066550,0.108203,0.199762,0.023240,-0.037710
2,0.196600,0.214445,0.368173,0.023968,0.207323,0.140139,0.172990,0.231019,0.156741,0.057226,...,0.197402,0.223793,0.121457,0.248807,0.134485,0.053503,-0.005610,0.253965,0.031899,0.059566
4,0.235489,0.227173,0.127394,0.410382,0.215954,0.186207,0.125068,0.196603,0.165264,0.034514,...,0.178055,0.245668,0.147579,0.284360,0.217076,-0.003941,0.037643,0.306750,0.137154,0.020968
5,0.190803,0.206530,0.097887,0.087230,0.464604,0.144950,0.159361,0.204884,0.264641,0.104493,...,0.197195,0.232923,0.117228,0.292623,0.170687,-0.020694,0.115293,0.297271,0.067951,0.051770
6,0.178282,0.238235,0.034447,0.220869,0.191487,0.317381,0.118250,0.163631,0.119401,0.021430,...,0.202794,0.247076,0.125801,0.255555,0.201974,-0.068777,0.099243,0.321076,0.102840,-0.017236
7,0.113396,0.054282,0.061550,0.069370,0.044484,0.109329,0.329688,0.092023,0.159883,0.051387,...,0.184071,0.179713,0.142222,0.192045,0.209176,0.035736,0.042035,0.159817,0.008022,0.022467
8,0.181002,0.228547,-0.006209,0.023346,0.133774,0.117255,0.194411,0.424899,0.064289,-0.004919,...,0.093679,0.136592,0.101116,0.173933,0.095452,-0.003312,0.050942,0.240088,0.051530,0.007182
11,0.214508,0.227264,0.109767,0.124790,0.237549,0.076848,0.107019,0.207917,0.551275,-0.003236,...,0.256072,0.166287,0.102690,0.366209,0.181682,-0.007782,0.147501,0.206234,-0.057620,0.064859
12,0.118927,0.175802,-0.016922,0.112255,0.159920,0.070012,0.077276,0.026258,0.103184,0.502334,...,0.163311,-0.091433,0.060118,0.163172,0.119053,0.080449,0.089125,0.118189,0.068853,-0.070408
13,0.164334,0.122046,0.005461,0.010883,0.181268,0.039717,0.019935,0.181695,0.130556,0.183309,...,0.149381,0.086856,0.028724,0.243780,0.006242,0.049899,0.215755,0.126097,0.028087,0.038319
16,0.147612,0.090343,0.144712,0.142199,0.070778,0.066558,0.073812,0.042875,0.078358,0.075163,...,0.060729,0.138263,0.155711,0.107511,0.168173,0.183749,0.047667,0.026967,0.032988,-0.069594
18,0.237601,0.198725,0.145390,0.165815,0.196673,0.121744,0.163083,0.219833,0.188723,0.003993,...,0.140359,0.142819,0.169787,0.277059,0.237151,0.033377,0.070336,0.170440,0.046006,0.048336
19,0.155100,0.192455,0.020605,0.095173,0.184119,0.069296,0.045375,0.125649,0.079685,0.140942,...,0.039737,0.070582,0.004733,0.204048,0.140478,0.021559,0.017926,0.198876,0.051412,0.056883
20,0.173414,0.044186,-0.017426,0.045449,0.174600,-0.006279,0.002655,0.162549,0.154483,0.059415,...,0.141680,-0.007405,-0.009672,0.313637,-0.049004,0.022929,0.229037,-0.037591,0.085221,0.052875
21,0.208074,0.132435,0.152194,0.113839,0.089849,0.046620,0.107635,0.210493,0.121436,0.122371,...,0.108251,0.230039,0.116190,0.244658,0.085353,0.033001,0.029180,0.074152,0.045891,0.043736
22,0.187717,0.219960,0.065009,0.177607,0.235705,0.128328,0.095061,0.260473,0.218132,-0.013717,...,0.142033,0.092326,0.105114,0.277822,0.172180,-0.006082,0.109070,0.241906,0.015731,0.076501
23,0.135206,0.228933,0.098896,-0.031135,0.084596,0.052817,0.169127,0.192549,0.066239,0.006328,...,0.137169,0.171526,0.104209,0.146902,0.203317,-0.022830,0.000101,0.117799,-0.133165,-0.007413
25,0.222587,0.166806,0.188189,0.045267,0.207256,0.048676,0.150926,0.189857,0.258609,-0.025527,...,0.159964,0.172972,0.134712,0.280908,0.198907,-0.015991,0.052934,0.064244,-0.078409,0.044735
26,0.159714,0.138266,0.079916,-0.081711,0.048495,0.003347,0.111647,0.160492,0.059694,0.076208,...,0.127021,0.213518,0.109099,0.258085,0.021007,0.098513,0.008177,-0.011436,0.000366,0.050728
27,0.141046,0.206997,0.166194,-0.020197,0.214703,0.136742,0.168807,0.198686,0.166922,0.080965,...,-0.003167,0.220063,0.110874,0.266231,0.232555,0.005164,0.031822,0.305568,-0.016385,0.102188
28,0.109332,0.215231,0.044340,0.104359,0.190965,0.101892,0.198738,0.186239,0.103464,0.050528,...,0.176809,0.218627,0.124430,0.280421,0.143976,-0.014017,-0.011490,0.225645,-0.005103,0.050044
29,0.151663,0.221406,0.075769,0.032404,0.069996,-0.016177,0.040235,0.157914,0.096413,0.028854,...,0.068164,0.179949,0.109494,0.159272,0.083708,-0.041004,-0.013937,-0.076911,-0.001765,0.039486
30,0.136833,0.186710,0.063886,0.077057,0.157194,0.088077,0.062497,0.067283,0.055026,0.007051,...,0.160664,0.077221,0.065727,0.074449,0.143564,0.076173,0.071668,0.145129,0.070659,-0.038160
32,0.123964,0.124085,0.075337,0.045406,0.187801,0.111292,0.107527,0.076201,0.146721,0.047261,...,0.389078,0.114886,0.102677,0.254367,0.121543,-0.008719,0.123756,0.213205,0.051568,-0.051364
33,0.154654,0.124277,0.127934,-0.003717,0.188320,0.021148,0.090017,0.074188,0.088673,0.011880,...,0.162621,0.364280,0.131512,0.271835,0.177876,0.064779,0.069032,0.080741,-0.008966,0.051313
36,0.202503,0.111887,0.146631,0.068399,0.185358,0.105399,0.109148,0.142813,0.154028,0.009469,...,0.150713,0.223602,0.279825,0.297624,0.217512,0.013940,0.041813,0.142911,-0.022520,0.053514
37,0.168292,0.229128,0.054949,0.122453,0.230139,0.067384,0.099248,0.218343,0.260045,-0.006619,...,0.138941,0.091852,0.071158,0.579180,0.152941,0.005814,0.172432,0.162745,-0.004544,0.076081
38,0.168530,0.183998,0.049509,0.069606,0.091211,0.075320,0.147002,0.167765,0.152676,0.041751,...,0.098736,0.138810,0.141221,0.224635,0.337550,-0.011640,-0.004019,-0.004071,0.026104,0.065758
39,-0.073478,-0.092188,0.011803,0.025478,-0.046397,-0.130076,-0.048712,-0.102047,-0.018324,0.018353,...,-0.033539,-0.107176,-0.025061,0.005244,-0.076908,0.362560,-0.030059,-0.246779,-0.071779,-0.017094
45,0.130021,0.033571,-0.021515,-0.040162,0.194344,0.013542,0.073355,0.227309,0.194594,0.012816,...,0.191197,0.034663,-0.025057,0.289554,0.010149,0.005448,0.478380,-0.102530,-0.006792,0.066382
46,0.069267,0.178473,0.090011,0.160279,0.101496,0.223068,0.186638,0.213387,0.012423,-0.000349,...,0.062980,0.207597,0.104561,0.195314,0.199210,-0.023709,-0.053230,0.431114,0.068597,0.011990
47,0.133199,0.106407,0.111656,0.109859,0.074349,0.148483,-0.076297,0.119680,0.029208,0.089261,...,0.051531,0.056091,0.082705,0.209660,-0.009241,0.012783,0.061945,0.178975,0.460511,0.022089
49,0.008851,0.083034,-0.000788,-0.033960,0.065887,0.061926,-0.009004,0.111627,0.060870,0.032228,...,0.005227,0.082721,0.020333,0.179679,-0.025648,0.025908,0.021141,0.163408,-0.054843,0.302410

In [5]:
pred_matrix.set_index("Unnamed: 0", inplace=True)
pred_matrix.index.name = None
pred_matrix

,0,1,2,4,5,6,7,8,11,12,...,32,33,36,37,38,39,45,46,47,49
0,0.253906,0.223051,0.091574,0.090883,0.231240,0.110326,0.130205,0.234756,0.162653,0.061016,...,0.160845,0.172629,0.128410,0.256112,0.158035,-0.039511,0.046160,0.117331,0.089593,0.093347
1,0.134354,0.261548,0.033560,0.058468,0.103166,0.045038,0.056721,0.214309,0.029347,0.092912,...,0.139250,0.086258,0.049607,0.149938,0.069138,0.023502,0.031032,-0.036034,0.036498,0.059739
2,0.144471,0.157685,0.184471,0.046664,0.165543,0.069165,0.172872,0.177144,0.144301,0.056962,...,0.179902,0.183381,0.147513,0.229170,0.181291,0.005630,0.028618,0.057090,0.102531,0.100047
4,0.200067,0.210091,0.106137,0.210803,0.173810,0.202097,0.142638,0.192170,0.162065,0.018940,...,0.133749,0.156804,0.154364,0.211737,0.151426,-0.057606,-0.008455,0.174414,0.190026,0.088025
5,0.214769,0.180553,0.108649,0.077590,0.271063,0.079113,0.140553,0.201198,0.189584,0.075220,...,0.155890,0.174821,0.132184,0.266307,0.164411,-0.013201,0.070461,0.132041,0.059535,0.044660
6,0.202093,0.197671,0.114590,0.189608,0.175836,0.215391,0.144887,0.192150,0.164091,0.011992,...,0.128727,0.175314,0.162225,0.213763,0.163236,-0.068974,-0.014479,0.166885,0.189098,0.088428
7,0.118464,0.121137,0.130859,0.063017,0.144546,0.067278,0.170053,0.142108,0.118560,0.039737,...,0.145712,0.176715,0.148078,0.207064,0.168634,-0.006466,-0.012675,0.036094,0.086468,0.046572
8,0.144395,0.248591,0.042850,0.059778,0.143075,0.074764,0.075901,0.267719,0.098487,0.071574,...,0.166966,0.123836,0.075709,0.205910,0.103731,-0.014980,0.029748,-0.004519,0.048520,0.070328
11,0.194593,0.167666,0.110714,0.067441,0.237813,0.104329,0.131631,0.216350,0.336623,0.026559,...,0.189035,0.159800,0.124883,0.347506,0.149390,-0.086841,0.150152,0.211688,0.083704,0.077855
12,0.055152,0.098046,0.088722,0.072901,0.087154,0.051245,0.077104,0.085598,0.019202,0.200640,...,0.140242,0.062627,0.069008,0.113979,0.054431,0.120355,0.112570,-0.037388,0.051708,0.020889
13,0.122820,0.124969,0.075154,0.071098,0.197619,0.072620,0.075301,0.148415,0.136641,0.154220,...,0.152073,0.093529,0.072014,0.204476,0.075109,0.044853,0.177329,0.071896,0.033658,0.028828
16,0.095846,0.105729,0.094951,0.078738,0.120659,0.070685,0.127901,0.122264,0.092154,0.081361,...,0.152814,0.141902,0.106562,0.181892,0.122840,0.040429,0.003714,0.000007,0.055922,0.020422
18,0.132275,0.129275,0.137311,0.068222,0.158358,0.076268,0.172466,0.148735,0.131843,0.038143,...,0.150193,0.177014,0.157253,0.212648,0.172712,-0.009303,-0.005065,0.049905,0.093448,0.045763
19,0.146214,0.185379,0.076406,0.050770,0.121695,0.049690,0.064549,0.138577,0.062164,0.027995,...,0.080156,0.093952,0.065938,0.164595,0.087783,0.009755,-0.012507,0.042030,0.071925,0.077873
20,0.118010,0.086221,0.060912,0.054255,0.173587,0.056142,0.046811,0.095645,0.213460,0.143349,...,0.116129,0.052552,0.057971,0.271247,0.047990,0.019460,0.261347,0.211364,0.029898,0.002087
21,0.151092,0.160044,0.151926,0.064721,0.159824,0.085005,0.157206,0.179504,0.114755,0.028685,...,0.143127,0.171372,0.156665,0.204757,0.165994,0.002632,-0.008157,0.066679,0.115307,0.101137
22,0.245295,0.206677,0.100560,0.127472,0.230972,0.168742,0.129254,0.239448,0.219421,-0.009695,...,0.149612,0.166478,0.138744,0.266256,0.166094,-0.108627,0.038011,0.165938,0.168295,0.137094
23,0.117660,0.151187,0.087809,-0.008830,0.115873,0.016861,0.093370,0.170646,0.077726,-0.001598,...,0.135199,0.127970,0.082723,0.184762,0.124467,-0.031101,-0.026709,0.018582,0.055801,0.146766
25,0.186078,0.140581,0.129646,0.063983,0.235131,0.087333,0.152166,0.198072,0.207475,0.024383,...,0.164868,0.178966,0.143400,0.267086,0.169925,-0.071106,0.050434,0.108731,0.076596,0.056318
26,0.079950,0.120770,0.108512,-0.008183,0.100835,0.002251,0.098498,0.140229,0.074731,0.035432,...,0.147843,0.116143,0.077639,0.177704,0.103496,0.058521,-0.007447,-0.035297,0.022892,0.072040
27,0.159002,0.137068,0.130760,0.080039,0.182463,0.117761,0.166552,0.166900,0.171799,0.015520,...,0.136576,0.176072,0.160970,0.231856,0.167372,-0.043551,0.006724,0.093838,0.112564,0.035031
28,0.149232,0.180282,0.107263,0.041392,0.120398,0.067233,0.096080,0.174210,0.065610,0.011443,...,0.121263,0.138132,0.091383,0.182893,0.134311,0.003863,-0.029059,0.029138,0.099310,0.142453
29,0.163045,0.180086,0.080007,0.064729,0.136787,0.073071,0.072051,0.148251,0.100370,0.004844,...,0.088267,0.109363,0.084653,0.174715,0.105422,-0.047766,-0.026747,0.066831,0.096957,0.084376
30,0.129517,0.188573,0.056484,0.038967,0.162740,0.024912,0.087415,0.172761,0.063371,0.159118,...,0.144460,0.127046,0.082448,0.159210,0.113641,0.080606,0.057584,0.062532,0.016997,0.038649
32,0.104287,0.142023,0.098598,0.047191,0.116161,0.054963,0.107116,0.165020,0.105399,0.070010,...,0.224306,0.132662,0.085038,0.184983,0.120333,-0.000660,0.015758,-0.020448,0.056761,0.060999
33,0.124731,0.128185,0.119435,0.061884,0.149544,0.069656,0.158066,0.150359,0.110510,0.052768,...,0.153584,0.192796,0.140303,0.214404,0.175182,-0.011939,-0.012310,0.036572,0.071021,0.051872
36,0.152595,0.140716,0.134947,0.075617,0.177188,0.099128,0.169961,0.162773,0.132460,0.033707,...,0.143726,0.194176,0.176827,0.215116,0.183592,-0.018411,-0.013129,0.070225,0.112991,0.056755
37,0.151880,0.198793,0.069447,0.068679,0.201447,0.071114,0.088200,0.239138,0.243008,0.011267,...,0.153245,0.124277,0.083567,0.410508,0.105248,-0.072706,0.159798,0.121253,0.044871,0.061204
38,0.129788,0.133255,0.127205,0.055520,0.155683,0.063292,0.165011,0.155428,0.119127,0.039478,...,0.149282,0.194418,0.143132,0.217432,0.188396,-0.027045,-0.010812,0.047230,0.086552,0.063337
39,-0.078306,-0.061304,-0.024948,-0.052951,-0.078196,-0.082214,-0.068675,-0.091132,-0.150467,0.075111,...,-0.045027,-0.075464,-0.071811,-0.070710,-0.082191,0.287701,-0.029008,-0.219487,-0.093641,-0.070694
45,0.135912,0.110634,0.067167,0.063721,0.197052,0.065244,0.067314,0.130963,0.222871,0.198930,...,0.137251,0.080284,0.064026,0.278341,0.067121,0.073792,0.321027,0.161721,0.026281,0.017469
46,0.156353,0.128661,0.020870,0.077587,0.203015,0.087479,0.047267,0.140099,0.213355,0.017554,...,0.066898,0.087955,0.059918,0.274683,0.076468,-0.079366,0.112414,0.438579,0.049021,0.004142
47,0.185813,0.178434,0.115858,0.122134,0.159556,0.147825,0.147438,0.175870,0.141487,0.004940,...,0.121455,0.163127,0.155926,0.197483,0.164643,-0.055018,-0.029829,0.106891,0.174863,0.093978
49,0.083489,0.148919,0.027088,-0.046530,0.049436,-0.023260,0.032649,0.154000,0.032670,-0.032564,...,0.102576,0.067250,0.022003,0.141577,0.063747,-0.051172,-0.070978,-0.040015,0.015680,0.152740

In [6]:
true_matrix.index = true_matrix.index.astype(int)
true_matrix.columns = true_matrix.columns.astype(int)
pred_matrix.index = pred_matrix.index.astype(int)
pred_matrix.columns = pred_matrix.columns.astype(int)

In [11]:
print(kendalltau(true_matrix.values.flatten(), pred_matrix.values.flatten())) # strong correlation :)

SignificanceResult(statistic=np.float64(0.5315238394823171), pvalue=np.float64(2.4269294896535112e-161))

In [12]:
# mask where row id == col id
diag_mask = pd.DataFrame(
    {col: true_matrix.index == col for col in true_matrix.columns},
    index=true_matrix.index
)

In [13]:
# on diagonal values
true_diag = true_matrix.values[diag_mask.values]
pred_diag = pred_matrix.values[diag_mask.values]
# off diagonal vales
true_offdiag = true_matrix.values[~diag_mask.values]
pred_offdiag = pred_matrix.values[~diag_mask.values]

In [14]:
print("on-diagonal: ", kendalltau(true_diag, pred_diag))
print("off-diagonal:", kendalltau(true_offdiag, pred_offdiag))
# also good correlation :)

on-diagonal:  SignificanceResult(statistic=np.float64(0.4509803921568628), pvalue=np.float64(0.00017642307615787115))
off-diagonal: SignificanceResult(statistic=np.float64(0.5114656031904288), pvalue=np.float64(3.41960048214161e-145))

In [15]:
test_ids = [45, 46, 47, 49]
true_test = true_matrix.loc[test_ids, test_ids]
pred_test = pred_matrix.loc[test_ids, test_ids]

In [16]:
kendalltau(true_test.values.flatten(), pred_test.values.flatten())

SignificanceResult(statistic=np.float64(0.3), pvalue=np.float64(0.11604743302854507))

In [17]:
# mask where row id == col id
test_diag_mask = pd.DataFrame(
    {col: true_test.index == col for col in true_test.columns},
    index=true_test.index
)

In [18]:
# on diagonal values
test_true_diag = true_test.values[test_diag_mask.values]
test_pred_diag = pred_test.values[test_diag_mask.values]
# off diagonal vales
true_offdiag = true_test.values[~test_diag_mask.values]
pred_offdiag = pred_test.values[~test_diag_mask.values]

In [19]:
print("on-diagonal: ", kendalltau(test_true_diag, test_pred_diag))
print("off-diagonal:", kendalltau(true_offdiag, pred_offdiag))
# strong in domain prediction, moderate off-domain prediction

on-diagonal:  SignificanceResult(statistic=np.float64(0.3333333333333334), pvalue=np.float64(0.75))
off-diagonal: SignificanceResult(statistic=np.float64(-0.1818181818181818), pvalue=np.float64(0.459023957331249))

In [20]:
# representation quality and predictive performance are inverse