In [7]:
# 7-7-2026

In [9]:
import pandas as pd
import numpy as np
from scipy.stats import kendalltau, spearmanr
import matplotlib.pyplot as plt

In [10]:
true_matrix = pd.read_csv("../transfer-matrix/rf_transfer_matrix.csv")
pred_matrix = pd.read_csv("../training/predicted_transfer_matrix_v2.csv")

In [11]:
true_matrix.set_index("Unnamed: 0", inplace=True)
true_matrix.index.name = None
true_matrix

,0,1,2,4,5,6,7,8,11,12,...,32,33,36,37,38,39,45,46,47,49
0,0.392727,0.291660,0.127238,0.058840,0.214817,0.084705,0.149056,0.182358,0.173877,0.026375,...,0.228505,0.243433,0.149609,0.275203,0.112525,-0.011557,0.116862,0.158796,0.025454,0.029928
1,0.142172,0.395760,0.030643,0.010376,0.180707,0.064432,0.056092,0.128808,0.097788,0.039590,...,0.167477,0.032806,0.029704,0.193033,0.055264,0.066550,0.108203,0.199762,0.023240,-0.037710
2,0.196600,0.214445,0.368173,0.023968,0.207323,0.140139,0.172990,0.231019,0.156741,0.057226,...,0.197402,0.223793,0.121457,0.248807,0.134485,0.053503,-0.005610,0.253965,0.031899,0.059566
4,0.235489,0.227173,0.127394,0.410382,0.215954,0.186207,0.125068,0.196603,0.165264,0.034514,...,0.178055,0.245668,0.147579,0.284360,0.217076,-0.003941,0.037643,0.306750,0.137154,0.020968
5,0.190803,0.206530,0.097887,0.087230,0.464604,0.144950,0.159361,0.204884,0.264641,0.104493,...,0.197195,0.232923,0.117228,0.292623,0.170687,-0.020694,0.115293,0.297271,0.067951,0.051770
6,0.178282,0.238235,0.034447,0.220869,0.191487,0.317381,0.118250,0.163631,0.119401,0.021430,...,0.202794,0.247076,0.125801,0.255555,0.201974,-0.068777,0.099243,0.321076,0.102840,-0.017236
7,0.113396,0.054282,0.061550,0.069370,0.044484,0.109329,0.329688,0.092023,0.159883,0.051387,...,0.184071,0.179713,0.142222,0.192045,0.209176,0.035736,0.042035,0.159817,0.008022,0.022467
8,0.181002,0.228547,-0.006209,0.023346,0.133774,0.117255,0.194411,0.424899,0.064289,-0.004919,...,0.093679,0.136592,0.101116,0.173933,0.095452,-0.003312,0.050942,0.240088,0.051530,0.007182
11,0.214508,0.227264,0.109767,0.124790,0.237549,0.076848,0.107019,0.207917,0.551275,-0.003236,...,0.256072,0.166287,0.102690,0.366209,0.181682,-0.007782,0.147501,0.206234,-0.057620,0.064859
12,0.118927,0.175802,-0.016922,0.112255,0.159920,0.070012,0.077276,0.026258,0.103184,0.502334,...,0.163311,-0.091433,0.060118,0.163172,0.119053,0.080449,0.089125,0.118189,0.068853,-0.070408
13,0.164334,0.122046,0.005461,0.010883,0.181268,0.039717,0.019935,0.181695,0.130556,0.183309,...,0.149381,0.086856,0.028724,0.243780,0.006242,0.049899,0.215755,0.126097,0.028087,0.038319
16,0.147612,0.090343,0.144712,0.142199,0.070778,0.066558,0.073812,0.042875,0.078358,0.075163,...,0.060729,0.138263,0.155711,0.107511,0.168173,0.183749,0.047667,0.026967,0.032988,-0.069594
18,0.237601,0.198725,0.145390,0.165815,0.196673,0.121744,0.163083,0.219833,0.188723,0.003993,...,0.140359,0.142819,0.169787,0.277059,0.237151,0.033377,0.070336,0.170440,0.046006,0.048336
19,0.155100,0.192455,0.020605,0.095173,0.184119,0.069296,0.045375,0.125649,0.079685,0.140942,...,0.039737,0.070582,0.004733,0.204048,0.140478,0.021559,0.017926,0.198876,0.051412,0.056883
20,0.173414,0.044186,-0.017426,0.045449,0.174600,-0.006279,0.002655,0.162549,0.154483,0.059415,...,0.141680,-0.007405,-0.009672,0.313637,-0.049004,0.022929,0.229037,-0.037591,0.085221,0.052875
21,0.208074,0.132435,0.152194,0.113839,0.089849,0.046620,0.107635,0.210493,0.121436,0.122371,...,0.108251,0.230039,0.116190,0.244658,0.085353,0.033001,0.029180,0.074152,0.045891,0.043736
22,0.187717,0.219960,0.065009,0.177607,0.235705,0.128328,0.095061,0.260473,0.218132,-0.013717,...,0.142033,0.092326,0.105114,0.277822,0.172180,-0.006082,0.109070,0.241906,0.015731,0.076501
23,0.135206,0.228933,0.098896,-0.031135,0.084596,0.052817,0.169127,0.192549,0.066239,0.006328,...,0.137169,0.171526,0.104209,0.146902,0.203317,-0.022830,0.000101,0.117799,-0.133165,-0.007413
25,0.222587,0.166806,0.188189,0.045267,0.207256,0.048676,0.150926,0.189857,0.258609,-0.025527,...,0.159964,0.172972,0.134712,0.280908,0.198907,-0.015991,0.052934,0.064244,-0.078409,0.044735
26,0.159714,0.138266,0.079916,-0.081711,0.048495,0.003347,0.111647,0.160492,0.059694,0.076208,...,0.127021,0.213518,0.109099,0.258085,0.021007,0.098513,0.008177,-0.011436,0.000366,0.050728
27,0.141046,0.206997,0.166194,-0.020197,0.214703,0.136742,0.168807,0.198686,0.166922,0.080965,...,-0.003167,0.220063,0.110874,0.266231,0.232555,0.005164,0.031822,0.305568,-0.016385,0.102188
28,0.109332,0.215231,0.044340,0.104359,0.190965,0.101892,0.198738,0.186239,0.103464,0.050528,...,0.176809,0.218627,0.124430,0.280421,0.143976,-0.014017,-0.011490,0.225645,-0.005103,0.050044
29,0.151663,0.221406,0.075769,0.032404,0.069996,-0.016177,0.040235,0.157914,0.096413,0.028854,...,0.068164,0.179949,0.109494,0.159272,0.083708,-0.041004,-0.013937,-0.076911,-0.001765,0.039486
30,0.136833,0.186710,0.063886,0.077057,0.157194,0.088077,0.062497,0.067283,0.055026,0.007051,...,0.160664,0.077221,0.065727,0.074449,0.143564,0.076173,0.071668,0.145129,0.070659,-0.038160
32,0.123964,0.124085,0.075337,0.045406,0.187801,0.111292,0.107527,0.076201,0.146721,0.047261,...,0.389078,0.114886,0.102677,0.254367,0.121543,-0.008719,0.123756,0.213205,0.051568,-0.051364
33,0.154654,0.124277,0.127934,-0.003717,0.188320,0.021148,0.090017,0.074188,0.088673,0.011880,...,0.162621,0.364280,0.131512,0.271835,0.177876,0.064779,0.069032,0.080741,-0.008966,0.051313
36,0.202503,0.111887,0.146631,0.068399,0.185358,0.105399,0.109148,0.142813,0.154028,0.009469,...,0.150713,0.223602,0.279825,0.297624,0.217512,0.013940,0.041813,0.142911,-0.022520,0.053514
37,0.168292,0.229128,0.054949,0.122453,0.230139,0.067384,0.099248,0.218343,0.260045,-0.006619,...,0.138941,0.091852,0.071158,0.579180,0.152941,0.005814,0.172432,0.162745,-0.004544,0.076081
38,0.168530,0.183998,0.049509,0.069606,0.091211,0.075320,0.147002,0.167765,0.152676,0.041751,...,0.098736,0.138810,0.141221,0.224635,0.337550,-0.011640,-0.004019,-0.004071,0.026104,0.065758
39,-0.073478,-0.092188,0.011803,0.025478,-0.046397,-0.130076,-0.048712,-0.102047,-0.018324,0.018353,...,-0.033539,-0.107176,-0.025061,0.005244,-0.076908,0.362560,-0.030059,-0.246779,-0.071779,-0.017094
45,0.130021,0.033571,-0.021515,-0.040162,0.194344,0.013542,0.073355,0.227309,0.194594,0.012816,...,0.191197,0.034663,-0.025057,0.289554,0.010149,0.005448,0.478380,-0.102530,-0.006792,0.066382
46,0.069267,0.178473,0.090011,0.160279,0.101496,0.223068,0.186638,0.213387,0.012423,-0.000349,...,0.062980,0.207597,0.104561,0.195314,0.199210,-0.023709,-0.053230,0.431114,0.068597,0.011990
47,0.133199,0.106407,0.111656,0.109859,0.074349,0.148483,-0.076297,0.119680,0.029208,0.089261,...,0.051531,0.056091,0.082705,0.209660,-0.009241,0.012783,0.061945,0.178975,0.460511,0.022089
49,0.008851,0.083034,-0.000788,-0.033960,0.065887,0.061926,-0.009004,0.111627,0.060870,0.032228,...,0.005227,0.082721,0.020333,0.179679,-0.025648,0.025908,0.021141,0.163408,-0.054843,0.302410

In [12]:
pred_matrix.set_index("Unnamed: 0", inplace=True)
pred_matrix.index.name = None
pred_matrix

,0,1,2,4,5,6,7,8,11,12,...,32,33,36,37,38,39,45,46,47,49
0,0.276859,0.207150,0.112482,0.069342,0.244638,0.088197,0.147709,0.203517,0.173118,0.072695,...,0.185331,0.215533,0.135818,0.241318,0.177609,0.070670,0.104026,0.159708,0.088330,0.104213
1,0.137639,0.320462,0.035962,0.034437,0.126660,0.018336,0.076997,0.163031,0.085054,0.071655,...,0.135584,0.110591,0.061245,0.158525,0.079161,0.097745,0.028000,0.107900,0.011754,-0.021262
2,0.230371,0.181944,0.208093,0.088256,0.223109,0.120664,0.157616,0.194072,0.203293,0.039788,...,0.156429,0.197150,0.155238,0.252127,0.195177,0.037762,0.170924,0.133349,0.120903,0.087147
4,0.189432,0.179861,0.114193,0.187005,0.164220,0.171245,0.198904,0.165055,0.165526,0.058206,...,0.191205,0.223199,0.176964,0.248961,0.194566,0.061413,0.116273,0.164203,0.179733,0.109276
5,0.264011,0.248477,0.122924,0.092032,0.310695,0.092436,0.133628,0.219480,0.257888,0.063636,...,0.189834,0.181949,0.130981,0.317822,0.174141,0.061610,0.159638,0.164327,0.096325,0.101216
6,0.179020,0.162322,0.119533,0.153471,0.147886,0.169814,0.188955,0.146351,0.154653,0.042654,...,0.176919,0.203783,0.182290,0.233397,0.199067,0.047737,0.116212,0.156530,0.165471,0.092127
7,0.159643,0.122503,0.112260,0.131069,0.138045,0.159707,0.193732,0.106410,0.142610,0.032447,...,0.169035,0.196703,0.180544,0.218625,0.173458,0.037530,0.109040,0.158212,0.141554,0.059913
8,0.198708,0.262280,0.074541,0.053996,0.166067,0.078243,0.121531,0.257917,0.116265,0.075453,...,0.144257,0.155125,0.105779,0.207092,0.141533,0.073428,0.068943,0.139886,0.060416,0.066920
11,0.227206,0.210507,0.154011,0.095580,0.282138,0.090765,0.130155,0.190922,0.343385,0.057880,...,0.220149,0.167451,0.130766,0.348721,0.161712,0.055855,0.251050,0.203064,0.091004,0.086062
12,0.069834,0.123723,0.025682,0.035993,0.044924,0.036654,0.050952,0.100636,0.062126,0.240398,...,0.100122,0.080842,0.044539,0.132814,0.064683,0.186715,0.061280,0.084387,0.041779,0.065360
13,0.123457,0.162280,0.041378,0.076862,0.098547,0.069432,0.094126,0.149060,0.086407,0.213747,...,0.150554,0.126627,0.082332,0.186437,0.096246,0.159232,0.072240,0.127561,0.073623,0.060436
16,0.156158,0.067693,0.087358,0.117887,0.146832,0.112663,0.143268,0.071637,0.126711,0.116050,...,0.204314,0.185435,0.140185,0.204810,0.141475,0.119488,0.095748,0.132353,0.110967,0.055367
18,0.194973,0.162708,0.148840,0.114622,0.170598,0.147030,0.170753,0.156407,0.161106,0.046628,...,0.168701,0.199843,0.170525,0.242433,0.206687,0.044603,0.131261,0.153327,0.146017,0.086364
19,0.122295,0.138618,0.027829,0.057261,0.098434,0.051956,0.059203,0.126413,0.067025,0.075889,...,0.025002,0.077457,0.057100,0.165386,0.072069,0.066772,0.059797,0.017783,0.052048,0.137887
20,0.103259,0.076064,0.075199,0.062910,0.150115,0.035442,0.040935,0.062795,0.187306,0.025210,...,0.116472,0.065646,0.041285,0.325889,0.047978,0.023185,0.265875,0.062788,0.056112,0.059229
21,0.167308,0.159711,0.083905,0.141252,0.143611,0.119856,0.138761,0.160701,0.131471,0.099304,...,0.172855,0.192996,0.122817,0.231501,0.156652,0.091486,0.090583,0.141330,0.137177,0.109706
22,0.215867,0.203309,0.123076,0.108524,0.188342,0.115818,0.137370,0.204764,0.159192,0.050042,...,0.136383,0.184614,0.131733,0.235734,0.199292,0.048017,0.119549,0.118245,0.136875,0.137842
23,0.174648,0.232362,0.058105,0.056804,0.125778,0.073938,0.117227,0.223004,0.081396,0.060037,...,0.122068,0.149518,0.101474,0.161881,0.136131,0.058012,0.070550,0.112429,0.072002,0.117849
25,0.228964,0.190305,0.160397,0.078041,0.256278,0.108018,0.147408,0.183476,0.250383,0.040342,...,0.194001,0.184704,0.148019,0.275258,0.185364,0.038316,0.175268,0.173854,0.108257,0.073038
26,0.118770,0.147412,0.037817,0.038489,0.093860,0.038221,0.067832,0.130794,0.088067,0.115602,...,0.093831,0.105533,0.056030,0.181750,0.080162,0.085970,0.083649,0.101259,0.043346,0.093266
27,0.210908,0.179299,0.178498,0.073639,0.210065,0.106047,0.132602,0.191426,0.190254,0.034734,...,0.131419,0.172135,0.130224,0.237123,0.182343,0.032709,0.157544,0.108650,0.106287,0.076300
28,0.156614,0.171600,0.076195,0.122835,0.139135,0.101438,0.123927,0.156420,0.131003,0.059540,...,0.114796,0.172695,0.109907,0.224458,0.150161,0.057515,0.091541,0.091571,0.119848,0.128912
29,0.147874,0.165095,0.045671,0.058673,0.129095,0.068127,0.077488,0.139734,0.100973,0.055229,...,0.064598,0.121117,0.072934,0.197758,0.112129,0.053203,0.083871,0.043516,0.088431,0.167186
30,0.114504,0.238088,0.038042,0.031851,0.079921,0.058968,0.084698,0.103046,0.052126,0.024305,...,0.133931,0.116427,0.081779,0.108702,0.103668,0.085369,0.015851,0.093783,0.050695,0.015976
32,0.156759,0.081446,0.070519,0.069574,0.143732,0.096499,0.158224,0.077813,0.157598,0.088843,...,0.331716,0.202794,0.148025,0.235654,0.147442,0.091738,0.151933,0.254696,0.087863,0.036642
33,0.193895,0.118582,0.113187,0.094700,0.155255,0.109193,0.168705,0.114950,0.134138,0.059649,...,0.192051,0.236306,0.156346,0.201878,0.186380,0.057624,0.103175,0.142048,0.120269,0.072714
36,0.194381,0.135611,0.126202,0.129894,0.158721,0.157749,0.198503,0.124897,0.150941,0.041152,...,0.195379,0.219838,0.199933,0.231879,0.201134,0.046236,0.119978,0.166904,0.139904,0.070686
37,0.181980,0.199380,0.037357,0.094423,0.220930,0.058821,0.073142,0.170351,0.231766,0.065483,...,0.182951,0.105919,0.070272,0.441963,0.097207,0.063458,0.256272,0.155609,0.075962,0.070523
38,0.209546,0.159897,0.114968,0.110078,0.165219,0.123679,0.151766,0.156265,0.143722,0.056040,...,0.151307,0.199119,0.146130,0.210577,0.218563,0.054015,0.112759,0.125896,0.131062,0.088307
39,-0.028652,-0.026540,-0.048984,-0.041803,-0.036218,-0.045770,-0.043293,-0.083010,-0.024810,0.041673,...,-0.005553,-0.020161,-0.044553,-0.016833,-0.029487,0.455792,-0.024284,-0.037622,-0.035935,-0.021957
45,0.137911,0.121212,0.099060,0.072210,0.195263,0.044743,0.050236,0.107943,0.255442,0.034511,...,0.162707,0.084669,0.050585,0.356602,0.080182,0.032486,0.336733,0.136284,0.065413,0.043768
46,0.163912,0.088599,0.103638,0.079859,0.154332,0.116239,0.184731,0.084967,0.197059,0.044794,...,0.273736,0.188967,0.167778,0.244233,0.162034,0.049877,0.158559,0.278944,0.088180,0.018962
47,0.199854,0.183359,0.131660,0.149081,0.165233,0.158230,0.179782,0.173170,0.152244,0.055613,...,0.168410,0.225921,0.172708,0.242689,0.218153,0.053588,0.121281,0.138711,0.177591,0.122854
49,0.170956,0.176409,0.045748,0.064579,0.130588,0.075790,0.105008,0.161429,0.090928,0.057550,...,0.089945,0.142805,0.092819,0.185942,0.119928,0.055525,0.080194,0.071571,0.082086,0.165038

In [13]:
true_matrix.index = true_matrix.index.astype(int)
true_matrix.columns = true_matrix.columns.astype(int)
pred_matrix.index = pred_matrix.index.astype(int)
pred_matrix.columns = pred_matrix.columns.astype(int)

In [14]:
print(kendalltau(true_matrix.values.flatten(), pred_matrix.values.flatten())) # strong correlation :)

SignificanceResult(statistic=np.float64(0.5395497236327687), pvalue=np.float64(3.451732321207611e-166))

In [15]:
# mask where row id == col id
diag_mask = pd.DataFrame(
    {col: true_matrix.index == col for col in true_matrix.columns},
    index=true_matrix.index
)

In [16]:
# on diagonal values
true_diag = true_matrix.values[diag_mask.values]
pred_diag = pred_matrix.values[diag_mask.values]
# off diagonal vales
true_offdiag = true_matrix.values[~diag_mask.values]
pred_offdiag = pred_matrix.values[~diag_mask.values]

In [17]:
print("on-diagonal: ", kendalltau(true_diag, pred_diag))
print("off-diagonal:", kendalltau(true_offdiag, pred_offdiag))
# also good correlation :)

on-diagonal:  SignificanceResult(statistic=np.float64(0.39393939393939403), pvalue=np.float64(0.0010521328939876514))
off-diagonal: SignificanceResult(statistic=np.float64(0.5193844304407352), pvalue=np.float64(1.164991909963433e-149))

In [18]:
test_ids = [45, 46, 47, 49]
true_test = true_matrix.loc[test_ids, test_ids]
pred_test = pred_matrix.loc[test_ids, test_ids]

In [20]:
kendalltau(true_test.values.flatten(), pred_test.values.flatten())

SignificanceResult(statistic=np.float64(0.39999999999999997), pvalue=np.float64(0.03262571359431892))

In [21]:
# mask where row id == col id
test_diag_mask = pd.DataFrame(
    {col: true_test.index == col for col in true_test.columns},
    index=true_test.index
)

In [22]:
# on diagonal values
test_true_diag = true_test.values[test_diag_mask.values]
test_pred_diag = pred_test.values[test_diag_mask.values]
# off diagonal vales
true_offdiag = true_test.values[~test_diag_mask.values]
pred_offdiag = pred_test.values[~test_diag_mask.values]

In [23]:
print("on-diagonal: ", kendalltau(test_true_diag, test_pred_diag))
print("off-diagonal:", kendalltau(true_offdiag, pred_offdiag))
# strong in domain prediction, moderate off-domain prediction

on-diagonal:  SignificanceResult(statistic=np.float64(0.6666666666666669), pvalue=np.float64(0.3333333333333333))
off-diagonal: SignificanceResult(statistic=np.float64(-0.0606060606060606), pvalue=np.float64(0.8405883696421891))

In [ ]:
# representation quality and predictive performance are inverse